### ISSUE TITLE
Status update delay not working

### ISSUE THREAD

**Issue by JornHermans** [apexad/homebridge-garagedoor-command#4]
First of all nice plugin works good,

One problem, it does not pull the new state i have put the delay to 1 second and even then its still not pulling the state update.

Can you fix this or am i doing somthing wrong?

                {
                        "accessory": "GarageCommand",
                        "name": "Garage Door",
                        "open": "curl --header \"Content-Type: text/plain\" --request POST --data \"OPENING\" http://localhost:8080/rest/items/Poort_Relay",
                        "close": "curl --header \"Content-Type: text/plain\" --request POST --data \"CLOSING\" http://localhost:8080/rest/items/Poort_Relay",
                        "state": "curl --header \"Content-Type: text/plain\" --request GET  http://localhost:8080/rest/items/Poort_Relay/state",
                        "status_update_delay": 15
                }

state is giving back OPEN = when opening finish, CLOSED = when closing finish, CLOSING = when its closing, OPENING = when its opening.

When i close the homekit app and reopen it its pulls the status.

**Comment by apexad** [comment]
The status update delay is not polling an actual status update, it’s simulated. It should be the real time it actually takes to open or close your garage if you do not want Siri to lie about the fact that the garage being opened or closed.

Otherwise I think the fix your asking is similar to what is being asked in #2, polling real status. I will look back into that as soon as I can, but unfortunately life has gotten pretty busy for me.
